name: Deployment  # Define the name of the workflow

on:
  push:  # Trigger the workflow when code is pushed to the specified branches
    branches:
      - main  # Trigger for pushes to the 'main' branch

jobs:
  lint:  # Define the 'lint' job to check code quality
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu runner
    steps:
      - name: Get code  # Checkout the repository code
        uses: actions/checkout@v3  # Use the checkout action to get the repository's code

      - name: Load & cache dependencies  # Load dependencies and manage caching
        id: cache-deps  # Set an ID for this step so we can reference it later
        uses: ./.github/actions/cached-deps  # Custom action to load and cache dependencies
        with:
          caching: 'false'  # Set caching to false (e.g., to ensure a fresh install)

      - name: Output information  # Output whether cache was used or not
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"  # Print the cache status

      - name: Lint code  # Run the linting process to check the code for errors or style issues
        run: npm run lint  # Run the lint command defined in the project's package.json

  test:  # Define the 'test' job to run the project's tests
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu runner
    steps:
      - name: Get code  # Checkout the repository code
        uses: actions/checkout@v3  # Use the checkout action to get the repository's code

      - name: Load & cache dependencies  # Load dependencies and manage caching
        uses: ./.github/actions/cached-deps  # Custom action to load and cache dependencies

      - name: Test code  # Run the tests for the project
        id: run-tests  # Set an ID for the test-running step
        run: npm run test  # Run the test command defined in the project's package.json

      - name: Upload test report  # Upload the test report if tests fail
        if: failure() && steps.run-tests.outcome == 'failure'  # Only run if the tests fail
        uses: actions/upload-artifact@v3  # Use GitHub's upload-artifact action to upload the test report
        with:
          name: test-report  # The name of the artifact to upload
          path: test.json  # The path to the test report file (assumed to be generated by the tests)

  build:  # Define the 'build' job to create the production-ready build
    needs: test  # The build job depends on the successful completion of the 'test' job
    runs-on: ubuntu-latest  # The job will run on the latest version of the Ubuntu runner
    steps:
      - name: Get code  # Checkout the repository code
        uses: actions/checkout@v3  # Use the checkout action to get the repository's code

      - name: Load & cache dependencies  # Load dependencies and manage caching
        uses: ./.github/actions/cached-deps  # Custom action to load and cache dependencies

      - name: Build website  # Build the website
        run: npm run build  # Run the build command defined in package.json

      - name: Upload artifacts  # Upload build artifacts for deployment
        uses: actions/upload-artifact@v3  # Use GitHub's upload-artifact action to upload the build output
        with:
          name: dist-files  # Name of the artifact (the build output)
          path: dist  # Path to the build output folder (assumed to be 'dist')

  deploy:  # Define the 'deploy' job to deploy the website
    permissions:  # Define permissions required for this job
      id-token: write  # Allow the job to write id tokens
      contents: read  # Allow reading repository contents
    needs: build  # The deploy job depends on the successful completion of the 'build' job
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu runner
    steps:
      - name: Get code  # Checkout the repository code
        uses: actions/checkout@v3  # Use the checkout action to get the repository's code

      - name: Get build artifacts  # Download the build artifacts for deployment
        uses: actions/download-artifact@v3  # Use GitHub's download-artifact action to download the build artifacts
        with:
          name: dist-files  # The artifact name to download (must match the 'name' from the build job)
          path: ./dist  # Path to download the build files to

      - name: Output contents  # List the contents of the downloaded build folder
        run: ls  # Run the 'ls' command to output the contents of the 'dist' folder

      - name: Deploy site  # Deploy the website to the hosting platform (e.g., AWS S3)
        id: deploy  # Set an ID for the deploy step
        uses: ./.github/actions/deploy-s3-docker  # Custom action to deploy to S3 using Docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key for authentication (stored as GitHub secrets)
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key for authentication (stored as GitHub secrets)
        with:
          bucket: gha-security-hosting-demo  # Name of the S3 bucket for deployment
          dist-folder: ./dist  # Path to the folder containing the build files to upload (the 'dist' folder)
          # bucket-region: us-east-2  # Specify the region of the S3 bucket (optional, commented out)

      - name: Output information  # Output the URL of the deployed site
        run: |
          echo "Live URL: ${{ steps.deploy.outputs.website-url }}"  # Print the live URL of the deployed website
